### ISSUE TITLE
clarification on the shapenet dataset

### ISSUE THREAD

**Issue by amiltonwong** [Regenerator/dpf-nets#4]
Hi, @Regenerator ,

As you mentioned,[ ShapeNetCore55.v2](https://github.com/Regenerator/dpf-nets#shapenetcore55) dataset is required. However, I only can find the downloadable file `ShapeNetCore.v2.zip` from the official ShapeNet website. Do you mean they are the same?

THX!

**Comment by Regenerator** [comment]
Yes, that's right. Generative and autoencoding experiments were performed on this data. To use it, you need to download it and unpack it before running repacking script.
